### ISSUE TITLE
warg will not read newick file

### ISSUE THREAD

**Issue by GoogleCodeExporter** [xavierdidelot/ClonalOrigin#4]
```
What steps will reproduce the problem?
1. Generate newick tree with mrbayes
2. Run Clonalorigin with tree from mrbayes
3. I get the error:
"Error in computeSiteLL: Invalid Local Tree, happened 0 times Error in 
computeSiteLL: Invalid Local Tree, happened 1 times..."

What is the expected output? What do you see instead?
I expect information on recombination rate and location parameters in my 
microbial genomes.

What version of the product are you using? On what operating system?
Latest clonalorigin. Scientific Linux release 6.4.

Please provide any additional information below.
I am attempting to determine recombination events in 40 microbial genomes. I 
can determine a phylogenetic tree for these genomes with very high confidence 
using mrbayes or ml methods. These methods take at most only a few hours, 
whereas clonalframe take has taken 3+ weeks and is still running. I'd like to 
use the mrbayes tree when I run clonalorigin, but warg will not accept the 
newick trees output by any software other than clonalframe, so I'm wondering if 
the required newick file format for warg is more specific. What are the 
specific requirements for the tree input into warg?


Thanks in advance for any help!
     Talia

```

Original issue reported on code.google.com by `tkara...@gmail.com` on 5 May 2014 at 4:36

**Comment by hoytpr** [comment]
Talia, I've found a workaround for when the `warg` command seems to generate this error, even with good trees (I use the ClonalOrigin nwk tree). My alignments generated over 1000 `warg` jobs to create the phase2.xml files. Most jobs completed quickly, but a few lingered on for weeks. The latter jobs either 1.) did not even start, or 2.) they gave 100 errors. 
After 100 of the following error messages:
`"Error in computeSiteLL: Invalid Local Tree, happened 100 times"` the job continued with:
`"Not reporting any more errors, fix this program!!"`, and then started running again:
`"...# 48% # 50% # 52%..."` etc.  When one of our nodes crashed, I restarted the job that had been running for weeks, and it completed in a few hours. I have since killed, then restarted all the `warg` jobs that were reporting errors, and they all completed within hours. This is a clunky workaround, but at least you'll project will be able to move forward. Just FYI, we are running a CentOS cluster of nodes with dual Intel Xeon E5-2620 “Sandy Bridge” hex core 2.0 GHz CPUs, with 32 GB of 1333 MHz RAM (our new supercomputer has just received funding!). 

Pete
